word_list = [
    "apple", "banana", "chocolate", "elephant", "friend", "guitar", "holiday",
    "internet", "juice", "kangaroo", "lion", "mountain", "notebook", "ocean",
    "pencil", "quartz", "rabbit", "sunshine", "turtle", "umbrella", "village",
    "watermelon", "xylophone", "yoga", "zebra", "airport", "butterfly",
    "carrot", "dolphin", "elephant", "flower", "guitar", "happiness", "island",
    "jacket", "kitchen", "laptop", "mountain", "night", "octopus", "piano",
    "question", "rabbit", "sun", "tiger", "umbrella", "vase", "water",
    "xylophone", "yawn", "zebra", "airplane", "beach", "cloud", "dog",
    "eleven", "fish", "garden", "hat", "jungle", "kettle",
    "lemon", "moon", "nest", "orange", "pencil", "quiet", "rabbit", "sun",
    "tree", "umbrella", "vase", "water", "xylophone", "yawn", "zebra", "apple",
    "banana", "cat", "dog", "elephant", "fish", "guitar", "hat", "igloo",
    "jacket", "kite", "lemon", "moon", "nest", "orange", "pencil", "quilt",
    "rose", "sun", "tree", "umbrella", "vase", "water", "xylophone", "yawn",
    "zebra", "ant", "bear", "cat", "dog", "elephant", "fox", "goat", "hat",
    "iguana", "jacket", "kangaroo", "lion", "mouse", "newt", "otter", "pig",
    "quokka", "rabbit", "seal", "turtle", "unicorn", "vulture", "walrus",
    "x-ray", "yak", "zebra", "apple", "butterfly", "cat", "dog", "elephant",
    "fox", "giraffe", "hat", "iguana", "jaguar", "kangaroo", "lion", "monkey",
    "newt", "otter", "penguin", "quokka", "rhinoceros", "snail", "tiger",
    "unicorn", "vulture", "whale", "xylophone", "yak", "zebra", "apple",
    "butterfly", "caterpillar", "dolphin", "elephant", "flamingo", "giraffe",
    "hippopotamus", "iguana", "jaguar", "kangaroo", "lemur", "meerkat",
    "narwhal", "octopus", "penguin", "quokka", "rhinoceros", "seagull",
    "toucan", "umbrella", "vulture", "walrus", "yak", "zebra"
]